#! /bin/zsh

dicoms2video() {
  localenv="$(pyenv version)"
  pyenv activate medconv

  dicoms=$(find ./ -type f \( -name "*dcm" \))
  while read -r dicom; do
    mp4="${dicom%.*}.mp4"
    if [ ! -f "$mp4" ]; then
      medconv --src "$dicom" - to-video
    else
      echo "$mp4 already exists. Skipping conversion."
    fi
  done <<<$dicoms

  pyenv activate "$localenv"
}
