#! /bin/zsh

video2gif() {
  if [[ $@ -ne 2 ]]; then
    echo >&2 "Provide a video path as the single parameter to this function."
    return 1
  fi
  input="$1"

  if [ ! -f "$input" ]; then
    echo >&2 "The video file \"$input\" does not exist!"
    return 1
  fi

  filename=$(basename $input)
  output="${filename%.*}.gif"

  echo "Convert $input to $output"

  TMP_DIR="/tmp/video2gif-frames-$filename"
  mkdir "$TMP_DIR"
  ffmpeg -i "$input" -vf scale=320:-1:flags=lanczos,fps=10 "$TMP_DIR/ffout%03d.png"
  convert -loop 0 "$TMP_DIR/ffout*.png" "$output"

  rm -r "$TMP_DIR"

  echo "Done!"
}
