#! /bin/zsh

videos2dicom() {
  localenv="$(pyenv version)"
  pyenv activate medconv

  videos=$(find ./ -type f \( -name "*avi" -or -name "*mp4" \))
  while read -r video; do
    dcm="${video%.*}.dcm"
    if [ ! -f "$dcm" ]; then
      medconv --src "$video" to-dicom --compressed True
    else
      echo "$dcm already exists. Skipping conversion."
    fi
  done <<<$videos

  pyenv activate "$localenv"
}
