#! /bin/zsh

set -x

video2gif() {
  # See: https://engineering.giphy.com/how-to-make-gifs-with-ffmpeg/
  if [[ "$#" -ne 2 ]]; then
    echo >&2 "Provide a video path (or '-') as input and output."
    return 1
  fi
  input="$1"
  output="$2"

  # read from stdin
  if [ "$input" = "-" ]; then
      input="pipe:"
  fi

  # write to stdout
  if [ "$output" = "-" ]; then
      output="pipe:"
  fi
      
  ffmpeg \
      -i "$input" \
      -filter_complex "[0:v] fps=12,scale=480:-1,split [a][b];[a] palettegen [p];[b][p] paletteuse" \
      "$output"
}
