#! /bin/bash
#
# This script creates symlinks for all *.symlink files in $HOME

set -e

# change to the root directory
cd "$(dirname "$0")/.."

# hardcode root location to ~/.dotfiles
# we will symlink the root directory to this location
DOTFILES_ROOT="$HOME/.dotfiles"

# shellcheck disable=SC1090
source "${PWD}/scripts/utils.sh"

# links this repositories' root folder to ~/.dotfiles
# skips if the folder already exists or if the repository
# is cloned to ~/.dotfiles already
link_file "$PWD" "$DOTFILES_ROOT"

install_dotfiles() {
  info 'installing dotfiles'
  find -H "$DOTFILES_ROOT" -maxdepth 3 -name '*.symlink' -not -path '*.git*' |
    while read -r src; do
      dst="$HOME/.$(basename "${src%.*}")"
      link_file "$src" "$dst"
    done
}

echo ''
install_dotfiles

echo ''
success '  All installed!'
