#! /bin/bash
#
# This script creates symlinks for all *.symlink files in $HOME

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e
source "$DOTFILES_ROOT/scripts/utils.sh"

install_dotfiles() {
  info 'installing dotfiles'
  find -H "$DOTFILES_ROOT" -maxdepth 3 -name '*.symlink' -not -path '*.git*' |
    while read -r src; do
      dst="$HOME/.$(basename "${src%.*}")"
      link_file "$src" "$dst"
    done
}

echo ''
install_dotfiles

echo ''
success '  All installed!'
