;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-semi&comma
	electric-newline-and-maybe-indent
	indent-for-tab-command
	markdown-outdent-or-delete
	org-self-insert-command
	smarter-move-beginning-of-line
	yaml-electric-backspace
	yaml-electric-dash-and-dot
	))

(setq mc/cmds-to-run-once
      '(
	c-electric-paren
	))
